name: magic_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  magic_sdk: 6.0.1
  magic_ext_tezos: ^0.2.6
  magic_ext_solana: ^0.3.5

  tezart:
    git: https://github.com/magiclabs/tezart
  solana: ^0.30.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  pinenacl: ^0.6.0  # Giữ lại nếu bạn đã thêm trước đó

flutter:
  uses-material-design: true